// Code generated by "stringer -type=CardNumber"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_A-0]
	_ = x[_2-1]
	_ = x[_3-2]
	_ = x[_4-3]
	_ = x[_5-4]
	_ = x[_6-5]
	_ = x[_7-6]
	_ = x[_8-7]
	_ = x[_9-8]
	_ = x[_10-9]
	_ = x[_J-10]
	_ = x[_Q-11]
	_ = x[_K-12]
	_ = x[Joker-13]
}

const _CardNumber_name = "_A_2_3_4_5_6_7_8_9_10_J_Q_KJoker"

var _CardNumber_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 21, 23, 25, 27, 32}

func (i CardNumber) String() string {
	if i < 0 || i >= CardNumber(len(_CardNumber_index)-1) {
		return "CardNumber(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardNumber_name[_CardNumber_index[i]:_CardNumber_index[i+1]]
}
